### PR TITLE
External sort example

### PR DESCRIPTION
**Pull request by TomTirapani**

### CODE REVIEW

**Comment by TomTirapani** [comment]
@lbwexler ... just doing some housekeeping of open issues / PRs.

This PR adds an example of using `GridModel.externalSort` to Toolbox - is it worth bringing it up to date and merging now that `externalSort` is no longer experimental?

**Comment by lbwexler** [comment]
yes!

**Comment by TomTirapani** [comment]
Great - I've updated the example to work with the latest hoist-react and to be more consistent with the other examples in Toolbox

**Comment by TomTirapani** [comment]
@lbwexler I caught this branch up with latest, modernized it for typescript, etc - in the interests of cleaning up branches hopefully we can finally merge it :)

**Pull request merged**
